version 0.35

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,14 +1,13 @@
-#!/bin/sh
+#!/bin/bash
 
-: ${R_HOME=`R RHOME`}
-if test -z "${R_HOME}"; then
-    echo "could not determine R_HOME"
-    exit 1
-fi
+: ${R_HOME:=`R RHOME`}
+if test -z "${R_HOME}"; then 
+   echo "could not determine R_HOME" 
+   exit 1 
+fi 
 
-cp src/Makevars.in src/Makevars
+REXEC=${R_HOME}/bin/R
 
-CC=`"${R_HOME}/bin/R" CMD config CC`
-if $CC -v 2>&1 | grep -q '^gcc version'; then
-  echo "PKG_CFLAGS = -Wall" >> src/Makevars
-fi
+eval $(grep R_HOME_DIR $REXEC | head -1)
+Makeconf=$(find $R_HOME_DIR/etc -print | egrep 'Makeconf$' )
+echo "Change default C/C++ compiler and default compile flags by editing $Makeconf"
